version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24

  build:
    commands:
      - echo "Download .env.production to .env"
      - aws s3 cp s3://original-apis/.env.production ./service/.env
      - echo "npm install"
      - cd service
      - npm install 

artifacts:
  files:
    - service/**/*
  base-directory: ./