version: 0.2

phases:
  build:
    commands:
      - echo "Download .env.production to .env"
      - aws s3 cp s3://original-apis/.env.production .env

artifacts:
  files:
    - service/**/*
  base-directory: ./