name: Deploy to LightSail

on:
  push:
    branches:
      - main # プッシュを監視するブランチ

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dokcer-compose 
        run: |
          docker compose -f docker-compose-ci.yml up -d
      - name: jest
        run: |
          docker exec -i o_apis_srv bash test_script.sh

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
  
      - name: Start CodePipeline execution
        run: |
          aws codepipeline start-pipeline-execution --name app-pipeline
